import { render, screen } from '@testing-library/react'
import { describe, expect, it } from 'vitest'
import { Panel } from '.'

describe('Panel', () => {
  // @blurb The panel root element must render with its data-testid so Playwright
  // @blurb and Vitest queries can locate it reliably without depending on fragile
  // @blurb CSS class names generated by CSS Modules.
  it('panel container is present', () => {
    render(<Panel header={<span />}><div /></Panel>)
    expect(screen.getByTestId('panel')).toBeInTheDocument()
  })

  // @blurb Content passed via the header prop must land inside the sticky
  // @blurb panel-header region so search inputs and toggle buttons remain
  // @blurb visible while the body scrolls below.
  it('header slot content is inside the panel-header', () => {
    render(
      <Panel header={<span data-testid="hdr-child">H</span>}><div /></Panel>,
    )
    expect(screen.getByTestId('panel-header')).toContainElement(
      screen.getByTestId('hdr-child'),
    )
  })

  // @blurb Body content must remain in the scrollable area and must not be
  // @blurb accidentally hoisted into the sticky header — hoisting would place
  // @blurb result lists above search inputs.
  it('children are inside the panel but outside the panel-header', () => {
    render(
      <Panel header={<span />}><span data-testid="body-child">B</span></Panel>,
    )
    expect(screen.getByTestId('panel')).toContainElement(screen.getByTestId('body-child'))
    expect(screen.getByTestId('panel-header')).not.toContainElement(
      screen.getByTestId('body-child'),
    )
  })
})
