// Code generated by tygo. DO NOT EDIT.
// GENERATED FILE — DO NOT EDIT BY HAND.
// Source: the toolkit's go/internal/observehttp response structs
//   (arcreview_corpus, benchmarks, benchmarks_aggregate, bugs,
//    chains, tasks, suggestions, memory_substrate).
// Regenerate: scripts/gen-types.sh  (reads a sibling toolkit clone;
//   set TOOLKIT_GO_DIR to override its location). The precommit gate
//   runs `scripts/gen-types.sh --check` and fails if this file has
//   drifted from the Go contract.

//////////
// source: arcreview_corpus.go

/**
 * ArcCorpusBucket is one labeled histogram cell for a snapshot-corpus
 * distribution chart (message-count or estimated-token ranges). Label is
 * the human-facing range; Count is the row tally in that range. Buckets
 * are emitted in a fixed order and zero-filled so the chart geometry is
 * stable across corpus growth.
 */
export interface ArcCorpusBucket {
  label: string;
  count: number /* int */;
}
/**
 * ArcCorpusStatsResponse is the arc-close snapshot-corpus telemetry payload
 * (GET /telemetry/snapshot-corpus/stats). It summarizes
 * arcreview_snapshot_corpus — the ML training substrate captured by the
 * arc-close review path — so corpus readiness is legible at a glance
 * instead of only via raw SQL.
 * BySource is zero-filled to {live, recovered} so the source-split chart
 * renders both cells even before live capture accrues. TupleCompleteRows
 * counts rows whose event_id joins an ArcCloseFilingReviewed event carrying
 * BOTH a non-empty decisions array and a non-empty arc_summary — the rows
 * that assemble a full (snapshot, labels) training tuple. DistinctSessions
 * is surfaced deliberately: the corpus is fire-rich but session-poor, and
 * ML exporters MUST hold out by session (a fire-level split leaks), so the
 * session count is the load-bearing readiness signal, not the row count.
 */
export interface ArcCorpusStatsResponse {
  total_rows: number /* int */;
  distinct_sessions: number /* int */;
  by_source: { [key: string]: number /* int */};
  truncated_rows: number /* int */;
  tuple_complete_rows: number /* int */;
  message_count_buckets: ArcCorpusBucket[];
  estimated_tokens_buckets: ArcCorpusBucket[];
}

//////////
// source: benchmarks.go

export interface TimeseriesPoint {
  bucket_start: number /* int64 */;
  model_name: string;
  layer: string;
  total: number /* int64 */;
  ok_count: number /* int64 */;
  args_ok_count?: number /* int64 */;
  interp_ok_count?: number /* int64 */;
  mean_wall_clock_ms: number /* float64 */;
}
export interface ShapeCard {
  task_shape: string;
  models: ModelMetrics[];
}
export interface RubricCard {
  rubric_name: string;
  deployable: boolean;
  verdict: string;
  verdict_note: string;
  retrigger_condition?: string;
  models: ModelMetrics[];
}
export interface TaskCard {
  task_id: string;
  task_shape: string;
  deployable: boolean;
  verdict?: string;
  verdict_note?: string;
  retrigger_condition?: string;
  models: ModelMetrics[];
}

//////////
// source: benchmarks_aggregate.go

/**
 * ModelMetrics mirrors observe_http::handlers::benchmarks::ModelMetrics.
 * All score fields are *float64 so omitted-data rows serialise as
 * `null` (matching Rust Option<f64>); verdictDistribution is omitted
 * entirely when no rows in the window carried a detected_tool label.
 */
export interface ModelMetrics {
  model_name: string;
  n_runs: number /* int64 */;
  accuracy: number | null;
  honesty: number | null;
  ranking_quality: number | null;
  within_budget: number | null;
  latency_normalized: number /* float64 */;
  tokens_normalized: number /* float64 */;
  latency_median_ms: number /* int64 */;
  tokens_median_total: number /* int64 */;
  verdict_distribution?: { [key: string]: number /* int64 */};
}

//////////
// source: bugs.go

/**
 * BugRow mirrors observe_http::handlers::bugs::BugRow. resolved_at and
 * qwen_task_id are nullable in the schema; we use *string so the encoder
 * emits explicit `null` (matching Rust's Option<String> serialization)
 * instead of dropping the keys.
 * The `tstype:"string | null,required"` override on the *string fields
 * pins the TS-side shape to `string | null` (not `string | undefined`);
 * without omitempty, Go marshals a nil pointer to JSON null, and the
 * TS consumer reads `null`, not a missing key. Same shape as
 * ModelMetrics' *float64 score fields, established in chain T8.
 */
export interface BugRow {
  id: number /* int64 */;
  project_id: string;
  slug: string;
  title: string;
  surface: string;
  severity: string;
  status: string;
  routed_suggestion_slug: string;
  filed_at: string;
  resolved_at: string | null;
  qwen_task_id: string | null;
}

//////////
// source: chains.go

/**
 * ChainRow mirrors observe_http::handlers::chains::ChainRow. Counts are
 * computed by correlated subqueries against the tasks table so the list
 * endpoint is one round-trip.
 */
export interface ChainRow {
  id: number /* int64 */;
  project_id: string;
  slug: string;
  status: string;
  total_tasks: number /* int64 */;
  pending: number /* int64 */;
  active: number /* int64 */;
  blocked: number /* int64 */;
  closed: number /* int64 */;
  cancelled: number /* int64 */;
  updated_at: string;
}
/**
 * ChainDetail mirrors observe_http::handlers::chains::detail — returns
 * the prose fields the list endpoint omits. design_decisions retired
 * from this projection-side cache in migration 065 (Phase 4 F2); the
 * EventTimeline reads it from ChainCreated/ChainEdited event payloads.
 */
export interface ChainDetail {
  id: number /* int64 */;
  project_id: string;
  slug: string;
  status: string;
  output: string;
  completion_condition: string;
  closure_summary: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: memory_substrate.go

/**
 * MemoryKindCount is one (key, count) row of the memory-substrate kind /
 * source distributions.
 */
export interface MemoryKindCount {
  key: string;
  count: number /* int64 */;
}
/**
 * MemoryRatePoint is a per-day MemoryWritten event count for the
 * event-rate timeseries (oldest day first).
 */
export interface MemoryRatePoint {
  day: string;
  count: number /* int64 */;
}
/**
 * MemorySubstrateStats is the telemetry payload for the vault-mediated
 * memory substrate (chain memory-substrate-within-vault), sourced from
 * proj_memories + MemoryWritten events. Deliberate first pass ahead of the
 * planned telemetry-unification push: it favours a working, tested read of
 * the real data over final information architecture, so it stays
 * DB-derived (no harness-dir filesystem reconciliation here).
 */
export interface MemorySubstrateStats {
  /**
   * TotalMemories is the live proj_memories row count — one per
   * vault/memory/<kind>/<name>.md entry.
   */
  total_memories: number /* int64 */;
  /**
   * ByKind is the user / feedback / project / reference distribution.
   */
  by_kind: MemoryKindCount[];
  /**
   * MemoryWrittenTotal is the lifetime MemoryWritten event count. It
   * exceeds TotalMemories because edits and since-deleted entries also
   * emitted (e.g. the migration re-forged entries later pruned).
   */
  memory_written_total: number /* int64 */;
  /**
   * BySource breaks MemoryWritten events down by their `source`
   * discriminator (migration / manual / user-correction / unset) — the
   * migration-vs-real-work split the substrate's validation surfaced.
   */
  by_source: MemoryKindCount[];
  /**
   * EventRate is the per-day MemoryWritten count, oldest day first.
   */
  event_rate: MemoryRatePoint[];
  /**
   * ParseContextHits is the count of grounding_events that surfaced at
   * least one memory/* candidate in source_refs — the reach of
   * parse_context's memory-aware resolution.
   */
  parse_context_hits: number /* int64 */;
  /**
   * OldestFiledAt / NewestFiledAt bound the live corpus (empty when no
   * memories exist).
   */
  oldest_filed_at: string;
  newest_filed_at: string;
}

//////////
// source: suggestions.go

/**
 * SuggestionRow mirrors the bugRow shape but reads native suggestion
 * vocabulary (priority, routed_bug_slug) and skips qwen_task_id —
 * suggestions never run through the Qwen filing-decision telemetry
 * surface that field captures for bugs. resolved_at is nullable so the
 * encoder emits explicit null for unresolved suggestions, matching the
 * bugRow convention.
 * Per chain `agent-suggestion-box` design, this handler queries the
 * canonical suggestions table directly rather than going through a
 * projection view; the audit-ledger integration that bugs accumulated
 * via proj_current_bugs lands later if/when suggestions also need that
 * shape. For now the suggestions read surface is event-driven via the
 * SuggestionReported / SuggestionResolved / SuggestionReopened /
 * SuggestionStamped payloads and the canonical CRUD table.
 */
export interface SuggestionRow {
  id: number /* int64 */;
  project_id: string;
  slug: string;
  title: string;
  surface: string;
  priority: string;
  status: string;
  routed_chain_slug: string;
  routed_task_slug: string;
  routed_bug_slug: string;
  resolved_commit_sha: string | null;
  filed_at: string;
  resolved_at: string | null;
}

//////////
// source: tasks.go

export interface TaskRow {
  id: number /* int64 */;
  chain_id: number /* int64 */;
  chain_slug: string;
  project_id: string;
  slug: string;
  position: number /* int64 */;
  status: string;
  problem_statement: string;
  updated_at: string;
}
/**
 * TaskContentMatch mirrors work_lib::tasks::TaskContentMatch — one row
 * per (task, field) pair that matched the search pattern, with a
 * ~200-char snippet centred on the first occurrence.
 */
export interface TaskContentMatch {
  chain_slug: string;
  chain_status: string;
  task_slug: string;
  task_status: string;
  field: string;
  snippet: string;
}
export interface SearchResponse {
  count: number /* int */;
  truncated: boolean;
  pattern: string;
  matches: TaskContentMatch[];
}
